language: bash
services: docker

before_install:
  # Wait 50 minutes to avoid travis timeout.
  # https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
  - travis_wait 50 docker build -t android-build-box:flutter .

script:
  - docker run -it --rm android-build-box:flutter flutter --version

after_script:
  - docker image ls

